# Generated by Django 5.1.4 on 2025-01-12 08:43

import django.db.models.deletion
import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_group_month_certificate_taskassistant'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата экзамена')),
                ('where', models.CharField(choices=[('Онлайн', 'Онлайн'), ('Оффлайн', 'Оффлайн')], max_length=50, verbose_name='Место провождение')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на экзамен(если онлайн)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=teacher.models.TeacherENG, to='teacher.teacherit', verbose_name='Учитель')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Прошел', 'Прошел'), ('Провалил', 'Провалил'), ('Пересдача', 'Пересдача')], max_length=50, verbose_name='Результат')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exam', verbose_name='Студент')),
                ('teacher_eng', models.ManyToManyField(to='teacher.teachereng', verbose_name='Учитель по английскому')),
                ('teacher_it', models.ManyToManyField(to='teacher.teacherit', verbose_name='Учитель по айти')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.TextField(verbose_name='Домашнее задание')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exam', verbose_name='Студент')),
            ],
        ),
    ]
