# Generated by Django 5.1.4 on 2025-01-12 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0002_dailyscore_exam_examresult_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.AddField(
            model_name='homework',
            name='data',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dailyscore',
            name='date',
            field=models.DateField(null=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='teacher_eng',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.teachereng', verbose_name='Учитель по английскому'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='teacher_it',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.teacherit', verbose_name='Учитель по айти'),
        ),
    ]
