# Generated by Django 5.1.4 on 2025-01-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='День недели')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Имя группы')),
                ('time_start', models.TimeField(verbose_name='Начало урока')),
                ('time_end', models.TimeField(verbose_name='Конец урока')),
                ('work_days', models.ManyToManyField(to='admin_panel.daysofweek', verbose_name='Дни занятий')),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='assistant-img/', verbose_name='Фото ассистента')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('responsibilities', models.TextField(verbose_name='Список обязанностей')),
                ('groups', models.ManyToManyField(blank=True, to='admin_panel.group', verbose_name='Группы')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='teacher-img/', verbose_name='Фото учителя')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('joined_date', models.DateField(verbose_name='Дата присоединения')),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт работы')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('groups', models.ManyToManyField(to='admin_panel.group', verbose_name='Группы')),
                ('work_days', models.ManyToManyField(to='admin_panel.daysofweek', verbose_name='Дни работы')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='teacher-img/', verbose_name='Фото учителя')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('specialization', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('English', 'English')], max_length=50, verbose_name='Направление')),
                ('joined_date', models.DateField(verbose_name='Дата присоединения')),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт работы')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('groups', models.ManyToManyField(to='admin_panel.group', verbose_name='Группы')),
                ('work_days', models.ManyToManyField(to='admin_panel.daysofweek', verbose_name='Дни работы')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='student-img/', verbose_name='Фото студента')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('specialization', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=50, verbose_name='Направление')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('joined_date', models.DateField(verbose_name='Дата начала обучения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.group', verbose_name='Группа')),
                ('teacher_eng', models.ManyToManyField(to='admin_panel.teachereng', verbose_name='Учитель по английскому')),
                ('teacher_it', models.ManyToManyField(to='admin_panel.teacherit', verbose_name='Учитель по айти')),
            ],
        ),
    ]
