# Generated by Django 5.1.4 on 2025-01-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher_eng',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher_it',
        ),
        migrations.RemoveField(
            model_name='teachereng',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='teachereng',
            name='work_days',
        ),
        migrations.RemoveField(
            model_name='teacherit',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='teacherit',
            name='work_days',
        ),
        migrations.DeleteModel(
            name='Assistant',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TeacherENG',
        ),
        migrations.DeleteModel(
            name='TeacherIT',
        ),
    ]
