# Generated by Django 5.1.4 on 2025-01-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_student_group_remove_student_teacher_eng_and_more'),
        ('assistant', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='month',
            field=models.IntegerField(default=1, verbose_name='Месяц'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=10)),
                ('total_points', models.IntegerField()),
                ('date_issued', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='На какую дату')),
                ('tasks', models.TextField(verbose_name='Список задач')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.assistant', verbose_name='Ассистент')),
            ],
        ),
    ]
