# Generated by Django 5.1.4 on 2025-01-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0003_group_month_certificate_taskassistant'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mentor-img/', verbose_name='Фото ментора')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон')),
                ('specialization', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Data Science', 'Data Science')], max_length=100, verbose_name='Специализация')),
                ('bio', models.TextField(blank=True, verbose_name='О менторе')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('joined_date', models.DateField(verbose_name='Дата начала работы')),
                ('groups', models.ManyToManyField(blank=True, to='admin_panel.group', verbose_name='Группы')),
            ],
        ),
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата сессии')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема сессии')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки ментора')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor', verbose_name='Ментор')),
                ('students', models.ManyToManyField(to='student.student', verbose_name='Студенты')),
            ],
        ),
    ]
