# Generated by Django 5.1.4 on 2025-01-11 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0002_remove_student_group_remove_student_teacher_eng_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='student-img/', verbose_name='Фото студента')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('specialization', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=50, verbose_name='Направление')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('joined_date', models.DateField(verbose_name='Дата начала обучения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.group', verbose_name='Группа')),
                ('teacher_eng', models.ManyToManyField(to='teacher.teachereng', verbose_name='Учитель по английскому')),
                ('teacher_it', models.ManyToManyField(to='teacher.teacherit', verbose_name='Учитель по айти')),
            ],
        ),
    ]
