# Generated by Django 5.1.4 on 2025-01-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0002_remove_student_group_remove_student_teacher_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='assistant-img/', verbose_name='Фото ассистента')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('responsibilities', models.TextField(verbose_name='Список обязанностей')),
                ('groups', models.ManyToManyField(blank=True, to='admin_panel.group', verbose_name='Группы')),
            ],
        ),
    ]
